version: '3.8'

services:
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend-runtime
    ports:
      - "3000:3000"
    # Automatically pulls key-value pairs from your local .env file
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always